url: -- # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Zachary Cabiling Cybersecurity Profile
description: Here is an overview of my skills are project in Cyber Security
